<div id="btmInq">
<h5><img src="http://www.shozen.com/physical_distribution/images/common/btminq_title.gif" width="386" height="24" alt="物流・倉庫に関するお問い合わせは" /></h5>
<p>ショーゼンのスタッフがどんなに些細なことでも親切、丁寧に、誠意を持って対応させていただきます。</p>
<div class="tel"><img src="http://www.shozen.com/physical_distribution/images/common/btminq_tel.png" alt="お電話でのお申込み・お問い合わせ 0799-62-6828" /></div>
<div class="btn"><a href="http://www.shozen.com/physical_distribution/inquiry/"><img src="http://www.shozen.com/physical_distribution/images/common/btminq_btn_off.png" alt="WEBからのお申込みお問い合わせはこちら" /></a></div>
</div><!-- /btmInq -->