<p id="logo"><a href="http://www.shozen.com/physical_distribution/"><img src="http://www.shozen.com/physical_distribution/images/common/h_logo.png" alt="株式会社ショーゼン" width="340" height="55" /></a></p>
<h1>兵庫県淡路島・神戸で物流、トラック配送のご用命ならショーゼンにお任せ下さい</h1>
<ul>
<li><a href="http://www.shozen.com/physical_distribution/privacy/">個人情報保護方針</a></li>
<li><a href="http://www.shozen.com/" target="_blank">ショーゼン総合TOPへ</a></li>
</ul>
<div id="tel"><img src="http://www.shozen.com/physical_distribution/images/common/h_tel.png" alt="お電話でのお問い合わせ 0799-62-6828" /></div>
<div id="btn"><a href="http://www.shozen.com/physical_distribution/inquiry"><img src="http://www.shozen.com/physical_distribution/images/common/h_btn_off.png" width="200" height="45" alt="WEBからのお問い合わせはこちら" /></a></div>