<ul class="sBnr">
<li><a href="/recruit/"><img src="/images/common/recruit_bnr_b.png" alt="採用情報" /></a></li>
<!-- li><a href="http://www.shozen.com/physical_distribution/result/"><img src="http://www.shozen.com/physical_distribution/images/common/s_btn_01_off.png" alt="豊富な実績" width="230" height="75" /></a></li -->
<!-- li><a href="http://www.shozen.com/physical_distribution/faq/"><img src="http://www.shozen.com/physical_distribution/images/common/s_btn_02_off.png" alt="よくある質問" width="230" height="75" /></a></li -->
<!-- li><a href="http://www.shozen.com/physical_distribution/voice/"><img src="http://www.shozen.com/physical_distribution/images/common/s_btn_03_off.png" alt="お客様の声" width="230" height="75" /></a></li -->
<li class="mb20"><a href="http://www.shozen.com/physical_distribution/inquiry/"><img src="http://www.shozen.com/physical_distribution/images/common/s_btn_04_off.png" alt="お問い合わせ" width="230" height="75" /></a></li>

<!--
<li>Facebookエリア</li>
-->

</ul>

<h4><img src="http://www.shozen.com/physical_distribution/images/common/s_title_bnr.png" width="230" height="25" alt="ショーゼングループサイト" /></h4>
<div id="sNews">

<ul class="sBnr2">
<li><a href="http://www.shozen.com/shozen_tour/"><img src="http://www.shozen.com/physical_distribution/images/common/s_bnr_bus.png" alt="ショーゼン観光バス" width="230" height="95" /></a></li>
<li><a href="http://www.shozen.com/shozen_tour/pilgrimage/"><img src="http://www.shozen.com/physical_distribution/images/common/s_bnr_tour.png" alt="ショーゼンツアー" width="230" height="95" /></a></li>
<li><a href="http://www.shozen.com/shozen_farm/"><img src="http://www.shozen.com/physical_distribution/images/common/s_bnr_farm.png" alt="ショーゼンファーム" width="230" height="95" /></a></li>
</ul>

</div><!-- /sNews -->