<div id="fInner">
<!--<p id="fNav"><a href="/shozen_tour/">ホーム</a>｜<a href="/shozen_tour/reason/">選ばれる理由</a>｜<a href="/shozen_tour/bustour/">物流・倉庫について</a>｜<a href="/shozen_tour/courtesybus/">安全な運送</a>｜<a href="/shozen_tour/pilgrimage/">管理体制</a>｜<a href="/shozen_tour/introductionbus/">実績紹介</a>｜<a href="/shozen_tour/staff/">Q&amp;A</a>｜<a href="/shozen_tour/voice/">お客様の声</a>｜<a href="/shozen_tour/company/">会社概要</a>｜<a href="/shozen_tour/inquiry/">お問い合わせ</a></p>-->
<div id="fAd">
<h5><a href="http://www.shozen.com/" target="_blank">株式会社 ショーゼン</a></h5>
<p>
〒656-2154 兵庫県淡路市木曽下162番地の3<br />
TEL：0799-62-6826<br />
FAX：0799-62-6827
</p>
</div>
<address>Copyright (C) 2012 shozen Co,. Ltd. All Rights Reserved. </address>
</div>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-75283835-1', 'auto');
  ga('send', 'pageview');

</script>