<p id="logo"><a href="http://www.shozen.com/shozen_farm/"><img src="images/common/h_logo.png" alt="株式会社ショーゼンファーム" width="460" height="55" /></a></p>
<h1>お客さまのニーズに応じた農産品を創造します。</h1>
<!--<ul>
<li><a href="/privacy/">お問い合わせ</a></li>
<li><a href="/company/">会社概要</a></li>
<li><a href="http://www.shozen.com/" target="_blank">株式会社ショーゼン</a></li>
</ul>-->
<div id="tel"><img src="images/common/h_tel.png" width="237" height="45" alt="お電話でのお問い合わせ 0799-64-9222" /></div>

<!--
<div id="btn"><a href="/inquiry"><img src="images/common/h_btn_off.png" width="200" height="45" alt="WEBからのお問い合わせはこちら" /></a></div>
-->