<div id="fInner">
<p id="fNav"><a href="http://www.shozen.com/shozen_tour/">ショーゼン観光バス</a>｜<a href="http://shozen.com/physical_distribution/">ショーゼン物流部門</a>｜<a href="http://www.shozen.com/shozen_farm/">ショーゼンファーム</a></p>
<div id="fAd">
<h5><a href="http://www.shozen.com/" target="_blank">株式会社 ショーゼン</a></h5>
<p>
■本社<br />
〒656-2154 兵庫県淡路市木曽下162番地の3<br />
TEL：0799-62-6888<br />
FAX：0799-62-6827<br />
受付時間：平日9:00～18:00（土曜日は17:00まで）<br />
※日曜、祝日は休日となります。

</p>
<p>
■神戸営業所<br />
〒651-2228 兵庫県神戸市西区見津が丘3丁目11-7<br />
TEL：078-995-2177<br />
FAX：078-995-2178<br />
受付時間：10:00～17:00（平日）<br />
※土曜、日曜、祝日は休日となります。
</p>
</div>
<address>Copyright (C) 2013 shozen Co,. Ltd. All Rights Reserved. </address>
</div>