<h4><img src="images/common/s_title_bnr.png" width="230" height="25" alt="ショーゼングループサイト" /></h4>
<div id="sNews">

<ul class="sBnr2">
<li><a href="http://www.shozen.com/shozen_tour/"><img src="images/common/s_bnr_bus.png" alt="ショーゼン観光バス" width="230" height="95" /></a></li>
<li><a href="http://www.shozen.com/shozen_tour/pilgrimage/"><img src="images/common/s_bnr_tour.png" alt="ショーゼンツアー" width="230" height="95" /></a></li>
</ul>

</div><!-- /sNews -->