<div id="btmInq">
<h5><img src="/shozen_tour/images/common/btminq_title.gif" width="497" height="24" alt="ツアーのお申込み、お問い合わせはお気軽に！" /></h5>
<p>ショーゼンのスタッフがどんなに些細なことでも親切、丁寧に、誠意を持って対応させていただきます。</p>
<div class="tel"><img src="/shozen_tour/images/common/btminq_tel.gif" width="270" height="60" alt="お電話でのお申込み・お問い合わせ 0799-62-6826" /></div>
<div class="btn"><a href="/shozen_tour/inquiry/"><img src="/shozen_tour/images/common/btminq_btn_off.png" width="235" height="60" alt="WEBからのお申込みお問い合わせはこちら" /></a></div>
</div><!-- /btmInq -->