<div id="fInner">
<p id="fNav"><a href="/shozen_tour/">トップページ</a>｜<a href="/shozen_tour/reason/">ショーゼン観光バスの特徴</a>｜<a href="/shozen_tour/bustour/">バス旅行・団体旅行</a>｜<a href="/shozen_tour/courtesybus/">送迎バス</a>｜<a href="/shozen_tour/pilgrimage/">巡礼・巡拝ツアー</a>｜<a href="/shozen_tour/introductionbus/">ひろ～いバス紹介</a>｜<a href="/shozen_tour/staff/">スタッフ紹介</a>｜<a href="/shozen_tour/voice/">お客様の声</a>｜<a href="/shozen_tour/faq/">よくある質問</a>｜<a href="/shozen_tour/company/">会社概要</a>｜<a href="/shozen_tour/inquiry/">お申込み・お問い合わせ</a></p>
<div id="fAd">
<h5><a href="http://www.shozen.com/" target="_blank">株式会社 ショーゼン</a></h5>
<p>
〒656-2154 兵庫県淡路市木曽下162番地の3<br />
TEL：0799-62-6826<br />
FAX：0799-62-6827
</p>
</div>
<address>Copyright (C) 2012 shozen Co,. Ltd. All Rights Reserved. </address>
</div>