<ul class="sBnr">
<li><a href="/shozen_tour/voice"><img src="/shozen_tour/images/common/s_btn_01_off.png" alt="お客様の声" width="230" height="65" /></a></li>
<li><a href="/shozen_tour/faq"><img src="/shozen_tour/images/common/s_btn_02_off.png" alt="よくあるご質問" width="230" height="65" /></a></li>
<li><a href="/shozen_tour/staff"><img src="/shozen_tour/images/common/s_btn_03_off.png" alt="スタッフ紹介" width="230" height="65" /></a></li>
<li class="mb20"><a href="/shozen_tour/company"><img src="/shozen_tour/images/common/s_btn_04_off.png" alt="会社概要" width="230" height="65" /></a></li>
<li><a href="http://ameblo.jp/shozen5" target="_blank"><img src="/shozen_tour/images/common/s_bnr_blog.png" alt="ショーゼンブログ" width="230" height="95" /></a></li>
</ul>

<h4><img src="/shozen_tour/images/common/s_title_news.png" width="230" height="25" alt="新着情報" /></h4>
<div id="sNews">

<dl>
<dt>2012/09/16</dt>
<dd>「お四国参り」ブログ更新しました。</dd>
<dt>2012/09/01</dt>
<dd>巡礼・巡拝絶賛営業中です。</dd>
<dt>2012/06/01</dt>
<dd>ショーゼン観光バスホームページをリニューアルいたしました！</dd>
</dl>

</div><!-- /sNews -->