<p id="logo"><a href="/shozen_tour/"><img src="/shozen_tour/images/common/h_logo.png" alt="ショーゼン観光バス" width="340" height="55" /></a></p>
<h1>兵庫県淡路島・神戸　観光貸切バス・団体旅行・送迎バス・お遍路・巡礼・巡拝なら</h1>
<ul>
<li><a href="/shozen_tour/privacy/">個人情報保護方針</a></li>
<li><a href="http://www.shozen.com/" target="_blank">ショーゼン総合TOPへ</a></li>
</ul>
<div id="tel"><img src="/shozen_tour/images/common/h_tel.png" alt="お電話でのお申込み・お問い合わせ 0799-62-6826" /></div>
<div id="btn"><a href="/shozen_tour/inquiry"><img src="/shozen_tour/images/common/h_btn_off.png" width="200" height="45" alt="WEBからのお申込み・お問い合わせ" /></a></div>