<ul class="sBnr">
<li class="mb20"><a href="/recruit/" target="_blank"><img src="/images/common/recruit_bnr_g.png" alt="採用情報" /></a></li>
<li><a href="/shozen_tour/voice"><img src="/shozen_tour/images/common/s_btn_01_off.png" alt="お客様の声" width="230" height="65" /></a></li>
<li><a href="/shozen_tour/faq"><img src="/shozen_tour/images/common/s_btn_02_off.png" alt="よくあるご質問" width="230" height="65" /></a></li>
<li><a href="/shozen_tour/management"><img src="/shozen_tour/images/common/s_btn_03_off.png" alt="運輸安全マネジメント" width="230" height="65" /></a></li>
<li><a href="http://www.shozen.com/#main03" target="_blank"><img src="/shozen_tour/images/common/s_btn_04_off.png" alt="会社概要" width="230" height="65" /></a></li>

<!--
<li><a href="http://www.bus.or.jp/safety/index.html" target="_blank"><img src="/shozen_tour/images/common/s_bnr_safety.png" alt="安全性評価認定（★）されました" /></a></li>
-->

</ul>

<h4><img src="/shozen_tour/images/common/s_title_news.png" width="230" height="25" alt="新着情報" /></h4>
<div id="sNews">

<dl>
<dt>2016/07/28</dt>
<dd>大型ラグジュアリーバスの<a href="http://www.shozen.com/shozen_tour/introductionbus/t_luxury/index.html" target="_blank">特設サイト</a>をオープンしました。</dd>
</dl>

<dl>
<dt>2016/01/06</dt>
<dd>全車両禁煙となりました。</dd>
</dl>
<dl>
<dt>2015/09/16</dt>
<dd>株式会社ショーゼン神戸営業所開設しました。</dd>
</dl>
<dl>
<dt>2015/01/20</dt>
<dd>セレガ27カジュアルプレミアムを導入しました。</dd>
</dl>
<dl>
<dt>2014/10/20</dt>
<dd>小型27新車バスを導入しました。</dd>
</dl>
<dl>
<dt>2014/03/04</dt>
<dd>セレガ27プレミアムを導入しました。</dd>
</dl>
<dl>
<dt>2012/09/16</dt>
<dd>「お四国参り」ブログ更新しました。</dd>
</dl>
<dl>
<dt>2012/09/01</dt>
<dd>巡礼・巡拝絶賛営業中です。</dd>
</dl>
<dl>
<dt>2012/06/01</dt>
<dd>ショーゼン観光バスホームページをリニューアルいたしました！</dd>
</dl>

</div><!-- /sNews -->